import csv
from datetime import date

today = date.today().isoformat()
FIELDS = [
    "id","title","agency","category","amount","city",
    "eligible_identity","min_age","max_age","income_limit",
    "housing_status","family_status","description",
    "apply_url","source_url","updated_at"
]

rows = [
# ── 身心障礙（25筆）──────────────────────────────────────
["dis-living-light","身障生活補助（輕度）","各縣市社會局","身心障礙","3579","全台","身心障礙者","","","符合所得限制","","","持輕度身障手冊、符合所得限制，每月3,579元生活補助","https://www.sfaa.gov.tw/","https://www.sfaa.gov.tw/",today],
["dis-living-mid","身障生活補助（中度）","各縣市社會局","身心障礙","4881","全台","身心障礙者","","","符合所得限制","","","持中度身障手冊、符合所得限制，每月4,881元生活補助","https://www.sfaa.gov.tw/","https://www.sfaa.gov.tw/",today],
["dis-living-heavy","身障生活補助（重度）","各縣市社會局","身心障礙","6183","全台","身心障礙者","","","符合所得限制","","","持重度身障手冊、符合所得限制，每月6,183元生活補助","https://www.sfaa.gov.tw/","https://www.sfaa.gov.tw/",today],
["dis-living-extreme","身障生活補助（極重度）","各縣市社會局","身心障礙","7485","全台","身心障礙者","","","符合所得限制","","","持極重度身障手冊、符合所得限制，每月7,485元生活補助","https://www.sfaa.gov.tw/","https://www.sfaa.gov.tw/",today],
["dis-assist-device","輔具補助","衛生福利部","身心障礙","80000","全台","身心障礙者","","","","","","醫師評估需求後，依項目補助輔具費用：輪椅最高24,700元、助聽器44,700元","https://repat.sfaa.gov.tw/","https://repat.sfaa.gov.tw/",today],
["dis-transport","身障交通補助","各縣市社會局","身心障礙","2400","全台","身心障礙者","","","","","","身障者搭乘大眾交通或復康巴士補助，每月最高2,400元","https://www.sfaa.gov.tw/","https://www.sfaa.gov.tw/",today],
["dis-employment","身障者就業補助","勞動部","身心障礙","12000","全台","身心障礙者","","","","","","身障者就業獎助及職場適應支援，雇主聘用每人每月可領補助","https://www.wda.gov.tw/","https://www.wda.gov.tw/",today],
["dis-vocational","身障職業訓練","勞動部","身心障礙","0","全台","身心障礙者","","","","","","身障者參加職業訓練課程費用全免，訓練期間可領生活津貼13,047元/月","https://www.wda.gov.tw/","https://www.wda.gov.tw/",today],
["dis-medical","身障醫療補助","各縣市社會局","身心障礙","12000","全台","身心障礙者","","","低收入或中低收入戶","","","具低收或中低收入資格身障者，醫療費用自付額補助，每年最高12,000元","https://www.sfaa.gov.tw/","https://www.sfaa.gov.tw/",today],
["dis-housing","身障住宅無障礙改善","各縣市社會局","身心障礙","100000","全台","身心障礙者","","","","","","身障者住宅增設無障礙設施補助，如扶手、斜坡、電梯，每戶最高10萬元","https://www.sfaa.gov.tw/","https://www.sfaa.gov.tw/",today],
["dis-tax-deduct","身障特別扣除額","財政部","身心障礙","207000","全台","身心障礙者","","","","","","申報綜所稅時每人扣除20.7萬元，稅率12%者省稅24,840元","https://www.mof.gov.tw/","https://www.mof.gov.tw/",today],
["dis-health-insure","身障健保費補助","健保署","身心障礙","6000","全台","身心障礙者","","","符合所得限制","","","中低收入身障者健保費由政府全額或部分補助","https://www.nhi.gov.tw/","https://www.nhi.gov.tw/",today],
["dis-vocational-rehab","職業重建服務","勞動部","身心障礙","0","全台","身心障礙者","","","","","","免費職業評量、職務再設計及就業陪伴服務，向職業重建中心申請","https://www.wda.gov.tw/","https://www.wda.gov.tw/",today],
["dis-care-home","身障居家照顧服務","衛生福利部","身心障礙","190","全台","身心障礙者","","","","","","身障者居家生活照顧服務補助，每小時最高190元，低收入戶免費","https://1966.gov.tw/","https://1966.gov.tw/",today],
["dis-care-day","身障日間照顧服務","衛生福利部","身心障礙","依評估","全台","身心障礙者","","","","","","無法自理生活的身障者日間照顧服務，依失能等級補助","https://1966.gov.tw/","https://1966.gov.tw/",today],
["dis-parking","身障停車位優惠","交通部","身心障礙","6000","全台","身心障礙者","","","","","","持手冊可申請身障停車識別證，享停車費優惠或免費，每年省3,000-6,000元","https://www.motc.gov.tw/","https://www.motc.gov.tw/",today],
["dis-income-support","身障者就業所得補助","勞動部","身心障礙","5000","全台","身心障礙者","","","","","","低薪身障就業者薪資差額補助，鼓勵就業","https://www.wda.gov.tw/","https://www.wda.gov.tw/",today],
["dis-sport","身障者運動及休閒補助","教育部","身心障礙","0","全台","身心障礙者","","","","","","身障者參加體育活動及競技訓練補助","https://www.sa.gov.tw/","https://www.sa.gov.tw/",today],
["dis-caregiver","身障照顧者喘息服務","衛生福利部","身心障礙","0","全台","身心障礙者家屬","","","","","","家庭照顧者申請喘息服務，每年最高14天免費居家照顧","https://1966.gov.tw/","https://1966.gov.tw/",today],
["dis-assistive-eval","輔具評估服務","衛生福利部","身心障礙","0","全台","身心障礙者","","","","","","免費輔具需求評估，協助申請適合輔具，由各縣市輔具資源中心辦理","https://repat.sfaa.gov.tw/","https://repat.sfaa.gov.tw/",today],
["dis-newborn-screen","新生兒聽力篩檢","衛生福利部","身心障礙","0","全台","一般民眾","","","","","有新生兒","新生兒出院前免費聽力篩檢，早期發現聽障盡早介入","https://www.mohw.gov.tw/","https://www.mohw.gov.tw/",today],
["dis-early-interv","早期療育服務","衛生福利部","身心障礙","0","全台","一般民眾","","6","","","有發展遲緩子女","0-6歲發展遲緩兒童享免費早期療育評估及聯合評估","https://www.sfaa.gov.tw/","https://www.sfaa.gov.tw/",today],
["dis-mental-health","精神疾病社區復健","衛生福利部","身心障礙","0","全台","精神障礙者","","","","","","精神疾病者可申請日間型社區復健中心服務，費用由健保或政府支付","https://www.mohw.gov.tw/","https://www.mohw.gov.tw/",today],
["dis-study","身障學生學費補助","教育部","身心障礙","30000","全台","身心障礙者","","22","","","","就讀大專院校身障學生學費補助，減免學雜費30-100%","https://www.moe.gov.tw/","https://www.moe.gov.tw/",today],
["dis-bus-free","身障者大眾運輸優惠","交通部","身心障礙","0","全台","重度身心障礙者","","","","","","重度以上身障者搭乘公車免費，中度以上搭乘台鐵半價","https://www.motc.gov.tw/","https://www.motc.gov.tw/",today],

# ── 農業農民（50筆）──────────────────────────────────────
["agri-rice-pay","稻作直接給付","農業部","農業","21000","全台","農民","","","","","","申報種稻農民按公頃補貼，每期10,500元，每年2期，建立穩定農業收入","https://www.coa.gov.tw/","https://www.coa.gov.tw/",today],
["agri-fallow","農地休耕補助","農業部","農業","45000","全台","農民","","","","","","農地休耕期間補貼，每年每公頃最高45,000元","https://www.coa.gov.tw/","https://www.coa.gov.tw/",today],
["agri-insurance","農保保費補助70%","農業部","農業","2184","全台","農民","","","","","","加入農保自付28元/月，政府補貼70%保費，享醫療傷病保障","https://www.coa.gov.tw/","https://www.coa.gov.tw/",today],
["agri-retirement","農民退休儲金（配對）","農業部","農業","120000","全台","農民","","","","","","農民每月自存，政府等額配對最高10,000元/月，為退休累積財源","https://www.coa.gov.tw/","https://www.coa.gov.tw/",today],
["agri-old-age","農保老年給付","農業部","農業","依年資","全台","農民","","","","","","農保投保年資×7,000元一次給付，60歲可申請","https://www.coa.gov.tw/","https://www.coa.gov.tw/",today],
["agri-machinery","農機具補助","農業部","農業","200000","全台","農民","","","","","","購置農機設備補助30-50%費用，如曳引機、收割機等，每件最高20萬","https://www.coa.gov.tw/","https://www.coa.gov.tw/",today],
["agri-greenhouse","溫網室農業設施補助","農業部","農業","500000","全台","農民","","","","","","興建溫室、網室等設施補助30-50%，最高50萬元","https://www.coa.gov.tw/","https://www.coa.gov.tw/",today],
["agri-organic","有機農業轉型補助","農業部","農業","120000","全台","農民","","","","","","慣行農業轉型有機農業，3年輔導期每公頃補助4萬元/年","https://www.coa.gov.tw/","https://www.coa.gov.tw/",today],
["agri-disaster","農業天然災害救助","農業部","農業","依損失","全台","農民","","","","","","颱風、洪水等天然災害導致農損，可申請每公頃最高10萬元救助","https://www.coa.gov.tw/","https://www.coa.gov.tw/",today],
["agri-crop-insure","農業保險保費補助","農業部","農業","依作物","全台","農民","","","","","","政府補助農作物保險保費50%，保障天然災害收入損失","https://www.coa.gov.tw/","https://www.coa.gov.tw/",today],
["agri-young-farmer","青年農民輔導計畫","農業部","農業","180000","全台","青年農民","20","45","","","","返鄉青農可獲3年輔導，每年補助6萬元，並提供農地媒合及技術指導","https://www.coa.gov.tw/","https://www.coa.gov.tw/",today],
["agri-smart","智慧農業科技補助","農業部","農業","300000","全台","農民","","","","","","導入IoT感測、自動灌溉等智慧農業技術，補助最高30萬元","https://www.coa.gov.tw/","https://www.coa.gov.tw/",today],
["agri-rural-renewal","農村再生補助","農業部","農業","依計畫","全台","農村社區","","","","","","農村社區整體建設補助，改善生活環境及農業發展","https://www.ardss.gov.tw/","https://www.ardss.gov.tw/",today],
["agri-water","農業用水補助","農業部","農業","依用量","全台","農民","","","","","","農業灌溉水費補助，減輕農民用水成本","https://www.coa.gov.tw/","https://www.coa.gov.tw/",today],
["agri-marketing","農產品行銷補助","農業部","農業","100000","全台","農民","","","","","","農產品品牌建立及行銷推廣補助，最高10萬元","https://www.coa.gov.tw/","https://www.coa.gov.tw/",today],
["agri-processing","農產加工補助","農業部","農業","300000","全台","農民","","","","","","設置農產加工設備補助50%費用，發展六級產業","https://www.coa.gov.tw/","https://www.coa.gov.tw/",today],
["agri-fishery","漁業補助（休漁補貼）","農業部漁業署","農業","依噸位","全台","漁民","","","","","","實施休漁期間漁船漁民生活補助，按船隻噸位計算","https://www.fa.gov.tw/","https://www.fa.gov.tw/",today],
["agri-fish-insure","漁業保險補助","農業部漁業署","農業","依費率","全台","漁民","","","","","","漁船及漁民意外保險保費補助50%","https://www.fa.gov.tw/","https://www.fa.gov.tw/",today],
["agri-fish-disaster","漁業天然災害救助","農業部漁業署","農業","依損失","全台","漁民","","","","","","颱風等天然災害造成漁業損失救助","https://www.fa.gov.tw/","https://www.fa.gov.tw/",today],
["agri-aqua","養殖漁業設施補助","農業部漁業署","農業","500000","全台","養殖漁民","","","","","","養殖設施（魚池、循環水系統）建設補助30-50%，最高50萬","https://www.fa.gov.tw/","https://www.fa.gov.tw/",today],
["agri-vet","畜牧業補助","農業部畜產試驗所","農業","依項目","全台","畜牧業者","","","","","","畜舍改善、廢水處理、設備更新等補助30-50%","https://www.coa.gov.tw/","https://www.coa.gov.tw/",today],
["agri-pork-price","毛豬價格穩定基金","農業部","農業","依差額","全台","養豬業者","","","","","","毛豬市場價格低於保證價格時，補貼業者差額損失","https://www.coa.gov.tw/","https://www.coa.gov.tw/",today],
["agri-forest","造林補助","農業部林業及自然保育署","農業","21000","全台","土地所有人","","","","","","造林每年每公頃補助21,000元，連補20年，含碳匯效益","https://www.forest.gov.tw/","https://www.forest.gov.tw/",today],
["agri-carbon","農業碳匯補助","農業部","農業","依碳量","全台","農民","","","","","","農業碳匯申請補助，種植友善環境作物可獲額外獎勵","https://www.coa.gov.tw/","https://www.coa.gov.tw/",today],
["agri-cooperative","農業合作社補助","農業部","農業","依計畫","全台","農業合作組織","","","","","","農業合作社成立及運作補助，促進農業規模化","https://www.coa.gov.tw/","https://www.coa.gov.tw/",today],
["agri-fertilizer","肥料補助","農業部","農業","依用量","全台","農民","","","","","","推廣有機肥料使用，部分費用由政府補助","https://www.coa.gov.tw/","https://www.coa.gov.tw/",today],
["agri-solar-farm","農地太陽能發電補助","農業部/經濟部","農業","依規模","全台","農民","","","","","","農業設施屋頂設置太陽能，農電共生補助","https://www.coa.gov.tw/","https://www.coa.gov.tw/",today],
["agri-loan","農業貸款利息補貼","農業部","農業","依貸款","全台","農民","","","","","","農民購地、農機、設施貸款利息補貼，降低融資成本","https://www.coa.gov.tw/","https://www.coa.gov.tw/",today],
["agri-land-bank","農地銀行服務","農業部","農業","0","全台","農民","","","","","","媒合農地出租承租，協助青農取得農地，免費服務","https://www.coa.gov.tw/","https://www.coa.gov.tw/",today],
["agri-flower","花卉產業補助","農業部","農業","依計畫","全台","花卉農民","","","","","","花卉品種改良、栽培技術、外銷推廣等補助","https://www.coa.gov.tw/","https://www.coa.gov.tw/",today],
["agri-tea","茶業發展補助","農業部","農業","依計畫","全台","茶農","","","","","","茶葉製程改良、品牌建立及外銷推廣補助","https://www.coa.gov.tw/","https://www.coa.gov.tw/",today],
["agri-fruit","果樹更新補助","農業部","農業","50000","全台","農民","","","","","","老舊果樹更新、品種改良補助，每公頃最高5萬","https://www.coa.gov.tw/","https://www.coa.gov.tw/",today],
["agri-seed","種苗補助","農業部","農業","依計畫","全台","農民","","","","","","優良種苗供應及補助，推廣台灣優良品種","https://www.coa.gov.tw/","https://www.coa.gov.tw/",today],
["agri-pesticide","農藥減量補助","農業部","農業","依計畫","全台","農民","","","","","","推動減少農藥使用，採用友善農業者獲補助獎勵","https://www.coa.gov.tw/","https://www.coa.gov.tw/",today],
["agri-training","農業技術訓練","農業部","農業","0","全台","農民","","","","","","免費農業技術訓練課程，含有機農業、智慧農業等","https://www.coa.gov.tw/","https://www.coa.gov.tw/",today],
["agri-health-check","農民健康檢查","衛生福利部","農業","0","全台","農民","","","","","","農保被保險人可申請每2年一次免費健康檢查","https://www.hpa.gov.tw/","https://www.hpa.gov.tw/",today],
["agri-disability-farm","農民職業災害補助","農業部","農業","依傷情","全台","農民","","","","","","農作業發生職業災害可申請農保職業傷病補助","https://www.coa.gov.tw/","https://www.coa.gov.tw/",today],
["agri-drought","旱災救助補助","農業部","農業","依損失","全台","農民","","","","","","乾旱導致農損，提供抽水費補助及作物損失救助","https://www.coa.gov.tw/","https://www.coa.gov.tw/",today],
["agri-export","農產品外銷補助","農業部","農業","100000","全台","農民","","","","","","農產品參加國際展覽及外銷推廣費用補助","https://www.coa.gov.tw/","https://www.coa.gov.tw/",today],
["agri-cold-chain","農產品冷鏈補助","農業部","農業","500000","全台","農業業者","","","","","","建置農產品冷鏈物流設施補助50%，保障農產品品質","https://www.coa.gov.tw/","https://www.coa.gov.tw/",today],
["agri-traceability","農產品追溯補助","農業部","農業","依計畫","全台","農民","","","","","","建立農產品生產履歷及追溯系統，補助系統建置費用","https://www.coa.gov.tw/","https://www.coa.gov.tw/",today],
["agri-rural-tourism","農村旅遊補助","農業部","農業","依計畫","全台","農場業者","","","","","","休閒農場認證及農村旅遊推廣活動補助","https://www.coa.gov.tw/","https://www.coa.gov.tw/",today],
["agri-mushroom","菇類栽培補助","農業部","農業","依計畫","全台","農民","","","","","","食用菇類栽培設備及技術輔導補助","https://www.coa.gov.tw/","https://www.coa.gov.tw/",today],
["agri-bamboo","竹業發展補助","農業部林業署","農業","依計畫","全台","竹農","","","","","","竹材採收利用及加工設備補助","https://www.forest.gov.tw/","https://www.forest.gov.tw/",today],
["agri-bee","養蜂補助","農業部","農業","依計畫","全台","養蜂業者","","","","","","蜂箱、蜂種及設備補助，推廣台灣養蜂產業","https://www.coa.gov.tw/","https://www.coa.gov.tw/",today],
["agri-drone","農業無人機補助","農業部","農業","200000","全台","農民","","","","","","購置農業無人機補助最高20萬，提升噴藥及管理效率","https://www.coa.gov.tw/","https://www.coa.gov.tw/",today],
["agri-salt","鹽田農業補助","農業部漁業署","農業","依計畫","全台","鹽田業者","","","","","","傳統鹽田保存及鹽業文化推廣補助","https://www.fa.gov.tw/","https://www.fa.gov.tw/",today],
["agri-herb","藥用植物栽培補助","農業部","農業","依計畫","全台","農民","","","","","","藥用植物（薑黃、黃耆等）栽培及加工補助","https://www.coa.gov.tw/","https://www.coa.gov.tw/",today],
["agri-compost","堆肥補助","農業部","農業","依計畫","全台","農民","","","","","","推廣農業廢棄物堆肥化補助，減少環境負擔","https://www.coa.gov.tw/","https://www.coa.gov.tw/",today],
["agri-income-protect","農業所得保險","農業部","農業","依費率","全台","農民","","","","","","農作物收入保險，價格下跌時補貼差額，穩定農民收入","https://www.coa.gov.tw/","https://www.coa.gov.tw/",today],

# ── 醫療健康（40筆）──────────────────────────────────────
["health-adult-check","成人預防保健（40歲以上）","衛生福利部","醫療健康","0","全台","一般民眾","40","","","","","40-64歲每3年一次、65歲以上每年一次免費成人健康檢查","https://www.hpa.gov.tw/","https://www.hpa.gov.tw/",today],
["health-cervix-screen","子宮頸癌篩檢","衛生福利部","醫療健康","0","全台","女性","30","","","","","30歲以上女性每年一次免費子宮頸抹片篩檢","https://www.hpa.gov.tw/","https://www.hpa.gov.tw/",today],
["health-breast-screen","乳癌篩檢","衛生福利部","醫療健康","0","全台","女性","45","","","","","45-69歲女性每2年一次免費乳房X光攝影篩檢","https://www.hpa.gov.tw/","https://www.hpa.gov.tw/",today],
["health-colon-screen","大腸癌篩檢","衛生福利部","醫療健康","0","全台","一般民眾","50","74","","","","50-74歲每2年一次免費糞便潛血篩檢","https://www.hpa.gov.tw/","https://www.hpa.gov.tw/",today],
["health-oral-screen","口腔癌篩檢","衛生福利部","醫療健康","0","全台","有吸菸或嚼檳榔習慣者","30","","","","","30歲以上有吸菸或嚼檳榔習慣者每2年一次免費口腔篩檢","https://www.hpa.gov.tw/","https://www.hpa.gov.tw/",today],
["health-flu-free","流感疫苗（公費）","衛生福利部","醫療健康","0","全台","特定對象","","","","","","65歲以上、孕婦、6歲以下幼兒等公費流感疫苗，每年秋冬接種","https://www.cdc.gov.tw/","https://www.cdc.gov.tw/",today],
["health-pneumo-senior","肺炎鏈球菌疫苗（老人）","衛生福利部","醫療健康","0","全台","老年人","65","","","","","65歲以上一生接種一次公費肺炎鏈球菌疫苗","https://www.cdc.gov.tw/","https://www.cdc.gov.tw/",today],
["health-hepatitis-b","B型肝炎篩檢","衛生福利部","醫療健康","0","全台","一般民眾","45","79","","","","45-79歲民眾可申請一次免費B型肝炎表面抗原及抗體篩檢","https://www.hpa.gov.tw/","https://www.hpa.gov.tw/",today],
["health-hepatitis-c","C型肝炎篩檢","衛生福利部","醫療健康","0","全台","一般民眾","45","79","","","","45-79歲（含原住民40歲）一次免費C型肝炎篩檢","https://www.hpa.gov.tw/","https://www.hpa.gov.tw/",today],
["health-kidney","腎臟病篩檢","衛生福利部","醫療健康","0","全台","特定高風險族群","","","","","","糖尿病、高血壓、65歲以上患者可申請免費腎功能篩檢","https://www.hpa.gov.tw/","https://www.hpa.gov.tw/",today],
["health-diabetes","糖尿病篩檢","衛生福利部","醫療健康","0","全台","一般民眾","40","","","","","40歲以上定期空腹血糖篩檢，納入成人健檢項目","https://www.hpa.gov.tw/","https://www.hpa.gov.tw/",today],
["health-hypertension","高血壓篩檢","衛生福利部","醫療健康","0","全台","一般民眾","18","","","","","成人預防保健含血壓量測，高風險族群定期追蹤","https://www.hpa.gov.tw/","https://www.hpa.gov.tw/",today],
["health-hpv-vaccine","HPV疫苗（公費）","衛生福利部","醫療健康","0","全台","青少年","","16","","","","國一女生及男生公費HPV疫苗接種，預防子宮頸癌及相關癌症","https://www.cdc.gov.tw/","https://www.cdc.gov.tw/",today],
["health-pregcheck","孕婦產前檢查","衛生福利部","醫療健康","0","全台","孕婦","","","","","懷孕","孕婦享14次公費產前檢查，含多項超音波及血液篩檢","https://www.hpa.gov.tw/","https://www.hpa.gov.tw/",today],
["health-prenatal-screen","孕婦產前唐氏症篩檢","衛生福利部","醫療健康","0","全台","孕婦","34","","","","懷孕","34歲以上孕婦可申請公費羊膜穿刺，預防唐氏症","https://www.hpa.gov.tw/","https://www.hpa.gov.tw/",today],
["health-nhi-major","重大傷病健保免自付","健保署","醫療健康","依費用","全台","重大傷病患者","","","","","","領有重大傷病卡者，門診住院自付額全免，減輕醫療負擔","https://www.nhi.gov.tw/","https://www.nhi.gov.tw/",today],
["health-rare","罕見疾病醫療補助","衛生福利部","醫療健康","依用藥","全台","罕見疾病患者","","","","","","罕見疾病患者特殊醫療費用及藥費由政府全額補助","https://www.tfrd.org.tw/","https://www.tfrd.org.tw/",today],
["health-mental","精神疾病醫療補助","衛生福利部","醫療健康","依就醫","全台","精神疾病患者","","","低收入戶","","","低收入精神疾病患者醫療費用減免及居家治療補助","https://www.mohw.gov.tw/","https://www.mohw.gov.tw/",today],
["health-palliative","安寧療護服務","健保署","醫療健康","0","全台","末期病人","","","","","","末期病人安寧療護費用納入健保，提供舒適善終照護","https://www.nhi.gov.tw/","https://www.nhi.gov.tw/",today],
["health-quit-smoke","戒菸補助","衛生福利部","醫療健康","0","全台","吸菸者","","","","","","提供免費戒菸諮詢、藥物補助，2次/年，每次8週","https://www.hpa.gov.tw/","https://www.hpa.gov.tw/",today],
["health-quit-betel","戒檳榔補助","衛生福利部","醫療健康","0","全台","嚼檳榔者","","","","","","提供戒檳榔諮詢及補助服務","https://www.hpa.gov.tw/","https://www.hpa.gov.tw/",today],
["health-dental-adult","成人牙齒預防保健","健保署","醫療健康","0","全台","一般民眾","18","","","","","18歲以上每半年一次免費牙齒塗氟及口腔檢查","https://www.nhi.gov.tw/","https://www.nhi.gov.tw/",today],
["health-dialysis","洗腎交通補助","各縣市社會局","醫療健康","2000","全台","洗腎患者","","","","","","因病需規律洗腎者，洗腎交通費補助每月最高2,000元","https://www.sfaa.gov.tw/","https://www.sfaa.gov.tw/",today],
["health-cancer-drug","癌症新藥補助","健保署","醫療健康","依用藥","全台","癌症患者","","","","","","癌症標靶藥物及免疫療法部分納入健保或專案補助","https://www.nhi.gov.tw/","https://www.nhi.gov.tw/",today],
["health-osteoporosis","骨質疏鬆篩檢","衛生福利部","醫療健康","0","全台","女性","65","","","","","65歲以上女性及特定高風險族群免費骨質密度篩檢","https://www.hpa.gov.tw/","https://www.hpa.gov.tw/",today],
["health-eye","老人視力篩檢","衛生福利部","醫療健康","0","全台","老年人","65","","","","","65歲以上老人免費視力及白內障篩檢","https://www.hpa.gov.tw/","https://www.hpa.gov.tw/",today],
["health-dementia","失智症篩檢","衛生福利部","醫療健康","0","全台","老年人","65","","","","","65歲以上老人可申請失智症初步篩檢，早期發現早期治療","https://www.hpa.gov.tw/","https://www.hpa.gov.tw/",today],
["health-nhi-foreign","新住民健保特別照護","健保署","醫療健康","0","全台","新住民","","","","","","入籍取得身分證後享與一般民眾相同健保權益","https://www.nhi.gov.tw/","https://www.nhi.gov.tw/",today],
["health-occupational","職業病補助","勞動部職安署","醫療健康","依損失","全台","勞工","","","","","","職業傷病認定後可申請醫療費用及失能補助","https://www.osha.gov.tw/","https://www.osha.gov.tw/",today],
["health-low-copay","低收入戶就醫免自付","健保署","醫療健康","依費用","全台","低收入戶","","","低收入戶","","","低收入戶就醫自付額全免，減輕就醫障礙","https://www.nhi.gov.tw/","https://www.nhi.gov.tw/",today],
["health-preterm","早產兒醫療補助","衛生福利部","醫療健康","依費用","全台","一般民眾","","","","","有早產兒","早產兒加護病房醫療費用超出健保給付部分，政府可補助","https://www.mohw.gov.tw/","https://www.mohw.gov.tw/",today],
["health-vaccine-pneu-child","幼兒肺炎鏈球菌疫苗","衛生福利部","醫療健康","0","全台","一般民眾","","5","","","有子女","5歲以下幼兒公費肺炎鏈球菌疫苗，預防肺炎腦膜炎","https://www.cdc.gov.tw/","https://www.cdc.gov.tw/",today],
["health-vaccine-rota","幼兒輪狀病毒疫苗","衛生福利部","醫療健康","0","全台","一般民眾","","1","","","有子女（2歲以下）","2024年起幼兒輪狀病毒疫苗納入公費，預防腹瀉","https://www.cdc.gov.tw/","https://www.cdc.gov.tw/",today],
["health-breast-pump","產後護理補助","各縣市政府","醫療健康","依計畫","全台","產婦","","","","","有新生兒","產後護理機構入住費用補助，各縣市金額不同","https://www.mohw.gov.tw/","https://www.mohw.gov.tw/",today],
["health-pregnancy-check","孕期營養補助","衛生福利部","醫療健康","0","全台","孕婦","","","","","懷孕","孕婦免費營養諮詢及葉酸等補充品補助","https://www.hpa.gov.tw/","https://www.hpa.gov.tw/",today],
["health-disability-rehab","身障復健補助","健保署","醫療健康","0","全台","身心障礙者","","","","","","身障者物理治療、職能治療等復健費用納入健保，減輕負擔","https://www.nhi.gov.tw/","https://www.nhi.gov.tw/",today],
["health-school-health","學童健康檢查","教育部/衛生部","醫療健康","0","全台","一般民眾","6","18","","","在學學生","國中小學童每年免費健康檢查，含視力、牙齒、體重等項目","https://www.hpa.gov.tw/","https://www.hpa.gov.tw/",today],
["health-subsidy-transport","就醫交通補助","各縣市政府","醫療健康","1000","全台","偏鄉居民","","","","","","偏鄉居民就醫交通費用補助，每月最高1,000元","https://www.mohw.gov.tw/","https://www.mohw.gov.tw/",today],
["health-telehealth","偏鄉遠距醫療","衛生福利部","醫療健康","0","全台","偏鄉居民","","","","","","偏鄉地區民眾可使用政府補助的遠距醫療服務","https://www.mohw.gov.tw/","https://www.mohw.gov.tw/",today],
["health-lung-screen","肺癌低劑量電腦斷層篩檢","衛生福利部","醫療健康","0","全台","高風險吸菸者","50","74","","","","50-74歲重度吸菸者，每2年一次免費低劑量肺部CT篩檢（2024年起）","https://www.hpa.gov.tw/","https://www.hpa.gov.tw/",today],
]

OUT = "data/subsidies_batch2.csv"
with open(OUT, "w", newline="", encoding="utf-8-sig") as f:
    writer = csv.writer(f)
    writer.writerow(FIELDS)
    writer.writerows(rows)

print(f"Batch2 完成：{len(rows)} 筆 → {OUT}")
